import { useState } from 'react';
import { Plus, Search, ShieldCheck, ShieldX, Brain, Package, Radar, CheckSquare, AlertTriangle, Info } from 'lucide-react';
import { toast } from 'sonner';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { normalizeSeverity, getSeverityIcon, findingTypeConfig, SEV } from '@/utils/severityHelpers';
import { authHeaders } from '@/hooks/useProjectData';
import FindingCard from '../findings/FindingCard';
import AddFindingDialog from '../findings/AddFindingDialog';
import DeleteConfirmDialog from '../shared/DeleteConfirmDialog';
import type { Finding, FindingPoc, FindingType, RetestStatus, Severity } from '@/utils/projectTypes';
import { API as API_BASE } from '@/utils/api';


// ─── TOIP Test Case types ─────────────────────────────────────────────────────

type ToipStatus = 'Secure' | 'Not Secure' | null;

type ToipTestCase = {
  id: string;
  category: string;
  title: string;
  description: string;
  severity: 'Critical' | 'High' | 'Medium' | 'Low';
  status: ToipStatus;
};

// Predefined TOIP test cases generated by Technieum OffSec Intelligence Portal
const TOIP_TEST_CASES: Omit<ToipTestCase, 'id' | 'status'>[] = [
  // Authentication & Session
  { category: 'Authentication & Session', title: 'Brute Force Protection', description: 'Verify account lockout after repeated failed login attempts and CAPTCHA enforcement.', severity: 'High' },
  { category: 'Authentication & Session', title: 'Session Fixation', description: 'Ensure session tokens are regenerated after successful authentication.', severity: 'High' },
  { category: 'Authentication & Session', title: 'Credential Exposure in Transit', description: 'Confirm all authentication requests are made over HTTPS with no credential leakage.', severity: 'Critical' },
  { category: 'Authentication & Session', title: 'MFA Bypass', description: 'Test for multi-factor authentication bypass using parameter tampering or response manipulation.', severity: 'Critical' },
  { category: 'Authentication & Session', title: 'Weak Password Policy', description: 'Verify enforcement of strong password requirements (length, complexity, history).', severity: 'Medium' },

  // Injection
  { category: 'Injection', title: 'SQL Injection', description: 'Test all input vectors for SQL injection vulnerabilities including error-based, blind, and time-based.', severity: 'Critical' },
  { category: 'Injection', title: 'Command Injection', description: 'Check for OS command injection in file operations, URL parameters, and form fields.', severity: 'Critical' },
  { category: 'Injection', title: 'LDAP Injection', description: 'Test LDAP queries for injection if directory services are in use.', severity: 'High' },
  { category: 'Injection', title: 'Template Injection (SSTI)', description: 'Identify server-side template injection in rendered views and email templates.', severity: 'High' },
  { category: 'Injection', title: 'XPath Injection', description: 'Validate XML/XPATH queries against injection if XML data stores are used.', severity: 'Medium' },

  // XSS & Client-Side
  { category: 'XSS & Client-Side', title: 'Reflected XSS', description: 'Test URL parameters, headers, and form fields for reflected cross-site scripting.', severity: 'High' },
  { category: 'XSS & Client-Side', title: 'Stored XSS', description: 'Verify that all user-supplied content stored in the database is properly sanitized on output.', severity: 'Critical' },
  { category: 'XSS & Client-Side', title: 'DOM-Based XSS', description: 'Review client-side JavaScript for unsafe DOM manipulation using user-controlled data.', severity: 'High' },
  { category: 'XSS & Client-Side', title: 'Content Security Policy', description: 'Confirm a strict CSP header is present and prevents inline script execution.', severity: 'Medium' },

  // Access Control
  { category: 'Access Control', title: 'IDOR - Horizontal Privilege Escalation', description: 'Attempt to access other users\' resources by manipulating object identifiers.', severity: 'High' },
  { category: 'Access Control', title: 'Vertical Privilege Escalation', description: 'Test whether lower-privileged users can access admin or elevated functionality.', severity: 'Critical' },
  { category: 'Access Control', title: 'Forced Browsing', description: 'Attempt direct URL access to authenticated/restricted pages without proper session.', severity: 'High' },
  { category: 'Access Control', title: 'API Authorization Controls', description: 'Verify all API endpoints enforce authorization and are not accessible with invalid/missing tokens.', severity: 'High' },

  // Cryptography & Data Exposure
  { category: 'Cryptography & Data Exposure', title: 'Sensitive Data in Responses', description: 'Review API and page responses for PII, credentials, tokens, or internal paths.', severity: 'High' },
  { category: 'Cryptography & Data Exposure', title: 'Insecure Direct Object References in Files', description: 'Test file download endpoints for path traversal and unauthorized file access.', severity: 'High' },
  { category: 'Cryptography & Data Exposure', title: 'Weak TLS Configuration', description: 'Verify TLS version, cipher suite strength, and certificate validity.', severity: 'Medium' },
  { category: 'Cryptography & Data Exposure', title: 'Sensitive Data in Local Storage', description: 'Check browser storage (localStorage, sessionStorage, cookies) for sensitive tokens or PII.', severity: 'Medium' },

  // Business Logic
  { category: 'Business Logic', title: 'Price/Quantity Manipulation', description: 'Test e-commerce flows for negative values, zero-price bypass, or quantity overflow.', severity: 'High' },
  { category: 'Business Logic', title: 'Workflow Bypass', description: 'Attempt to skip required steps in multi-step processes (checkout, approval, verification).', severity: 'High' },
  { category: 'Business Logic', title: 'Race Condition', description: 'Test concurrent requests on critical operations (transfers, coupon redemption, votes).', severity: 'Medium' },

  // Infrastructure
  { category: 'Infrastructure', title: 'Security Headers', description: 'Validate presence of HSTS, X-Frame-Options, X-Content-Type-Options, and Referrer-Policy headers.', severity: 'Low' },
  { category: 'Infrastructure', title: 'CORS Misconfiguration', description: 'Test CORS policy for overly permissive origins and credential inclusion.', severity: 'High' },
  { category: 'Infrastructure', title: 'Server Information Disclosure', description: 'Check for version banners, stack traces, and directory listings in error responses.', severity: 'Low' },
  { category: 'Infrastructure', title: 'Open Redirect', description: 'Test redirect parameters for open redirect to external malicious domains.', severity: 'Medium' },
];

// ─── SCA config (mirrors findingTypeConfig shape) ────────────────────────────

const SCA_CONFIG = {
  label: 'SCA',
  icon: <Package className="h-4 w-4" />,
  color: 'text-orange-400',
  bgColor: 'bg-orange-500/10',
  borderColor: 'border-orange-500/20',
};

const TOIP_CONFIG = {
  label: 'TOIP',
  icon: <Radar className="h-4 w-4" />,
  color: 'text-orange-400',
  bgColor: 'bg-orange-500/10',
  borderColor: 'border-orange-500/20',
};

// ─── Props ────────────────────────────────────────────────────────────────────

type Props = {
  findings: Finding[];
  pocs: Record<string, FindingPoc[]>;
  projectId: string;
  projectName: string;
  userId: string;
  getUsername: (uid: string | null | undefined) => string;
  onFindingAdded: (finding: Finding, pocs: FindingPoc[]) => void;
  onFindingDeleted: (findingId: string) => void;
  onPocAdded: (findingId: string, poc: FindingPoc) => void;
  onPocRemoved: (findingId: string, pocId: string) => void;
  onFindingUpdated: (finding: Finding) => void;
  onRefresh: () => Promise<void>;
};

// ─── Component ────────────────────────────────────────────────────────────────

export default function FindingsTab({
  findings, pocs, projectId, projectName, userId,
  getUsername, onFindingAdded, onFindingDeleted,
  onPocAdded, onPocRemoved, onFindingUpdated, onRefresh,
}: Props) {
  const [searchQuery, setSearchQuery]           = useState('');
  const [severityFilter, setSeverityFilter]     = useState<string>('all');
  const [activeFindingTab, setActiveFindingTab] = useState<string>('pentest');
  const [expandedFinding, setExpandedFinding]   = useState<string | null>(null);
  const [addFindingOpen, setAddFindingOpen]     = useState(false);
  const [currentFindingType, setCurrentFindingType] = useState<FindingType>('pentest');
  const [deletingFindingId, setDeletingFindingId]   = useState<string | null>(null);

  // ── TOIP state ──
  const [toipTestCases, setToipTestCases] = useState<ToipTestCase[]>(() =>
    TOIP_TEST_CASES.map((tc, i) => ({ ...tc, id: `toip-${i}`, status: null }))
  );
  const [toipSearch, setToipSearch]               = useState('');
  const [toipCategoryFilter, setToipCategoryFilter] = useState('all');
  const [toipSeverityFilter, setToipSeverityFilter] = useState('all');

  // ── helpers ──
  const getFindingsByType = (type: FindingType) =>
    findings.filter(f => (f.finding_type || 'pentest') === type);

  const filteredFindingsByType = (type: FindingType) =>
    getFindingsByType(type).filter(f => {
      const ms = f.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
        (f.description?.toLowerCase().includes(searchQuery.toLowerCase()) ?? false);
      const mv = severityFilter === 'all' || normalizeSeverity(f.severity) === severityFilter;
      return ms && mv;
    });

  const openAddFindingDialog = (type: FindingType) => {
    setCurrentFindingType(type);
    setAddFindingOpen(true);
  };

  const handleDeleteRequest = (findingId: string) => {
    const f = findings.find(f => f.id === findingId);
    if (!f || !userId || f.created_by !== userId) { toast.error('You can only delete your own findings'); return; }
    setDeletingFindingId(findingId);
  };

  const confirmDelete = async () => {
    if (!deletingFindingId) return;
    try {
      const res = await fetch(`${API_BASE}/findings/${deletingFindingId}`, { method: 'DELETE', headers: authHeaders() });
      if (!res.ok) { const e = await res.json(); toast.error('Failed: ' + (e.message ?? res.statusText)); return; }
      onFindingDeleted(deletingFindingId);
      toast.success('Finding deleted');
    } catch { toast.error('Failed to delete finding'); }
    finally { setDeletingFindingId(null); }
  };

  const handleUpdateRetestStatus = async (findingId: string, status: RetestStatus) => {
    try {
      const res = await fetch(`${API_BASE}/findings/${findingId}`, {
        method: 'PATCH', headers: authHeaders(),
        body: JSON.stringify({ retest_status: status, retest_date: new Date().toISOString(), retested_by: userId }),
      });
      if (!res.ok) { const e = await res.json(); toast.error('Failed: ' + (e.message ?? res.statusText)); return; }
      const updated: Finding = await res.json();
      onFindingUpdated(updated);
      toast.success(`Retest status updated to "${status}"`);
    } catch { toast.error('Failed to update retest status'); }
  };

  // ── TOIP toggle ──
  const toggleToipStatus = (id: string, next: ToipStatus) => {
    setToipTestCases(prev =>
      prev.map(tc => tc.id === id ? { ...tc, status: tc.status === next ? null : next } : tc)
    );
  };

  // ── Standard findings list renderer ──
  // `displayConfig` lets callers override the label/colors shown in the UI
  // without changing which findings are fetched (used by the SCA tab which
  // reuses the 'sast' finding type but must display "SCA" everywhere).
  const renderFindingsList = (
    type: FindingType,
    displayConfig?: { label: string; icon: React.ReactNode; bgColor: string; color: string; borderColor: string }
  ) => {
    const typeFindings = filteredFindingsByType(type);
    // Use the override if provided, otherwise fall back to the type's own config
    const config = displayConfig ?? findingTypeConfig[type];

    return (
      <div className="space-y-4">
        {/* Filters row */}
        <div className="flex flex-col sm:flex-row gap-4">
          <div className="relative flex-1">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
            <Input
              placeholder={`Search ${config.label.toLowerCase()} findings...`}
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="pl-10 bg-secondary/50"
            />
          </div>
          <Select value={severityFilter} onValueChange={setSeverityFilter}>
            <SelectTrigger className="w-full sm:w-40 bg-secondary/50"><SelectValue placeholder="Severity" /></SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Severity</SelectItem>
              <SelectItem value="Critical">Critical</SelectItem>
              <SelectItem value="High">High</SelectItem>
              <SelectItem value="Medium">Medium</SelectItem>
              <SelectItem value="Low">Low</SelectItem>
              <SelectItem value="Informational">Informational</SelectItem>
            </SelectContent>
          </Select>
          <Button variant="default" className="gradient-technieum" onClick={() => openAddFindingDialog(type)}>
            <Plus className="h-4 w-4 mr-2" />Add {config.label} Finding
          </Button>
        </div>

        {/* Severity summary cards */}
        <div className="grid grid-cols-2 md:grid-cols-5 gap-3">
          {(['Critical', 'High', 'Medium', 'Low', 'Informational'] as Severity[]).map(sev => {
            const count = typeFindings.filter(f => normalizeSeverity(f.severity) === sev).length;
            const { bg, text, border } = SEV[sev];
            return (
              <Card key={sev} className={`p-4 border ${border} ${bg}`}>
                <div className="flex items-center justify-between">
                  <div>
                    <p className={`text-2xl font-bold ${text}`}>{count}</p>
                    <p className="text-xs text-muted-foreground">{sev}</p>
                  </div>
                  {getSeverityIcon(sev)}
                </div>
              </Card>
            );
          })}
        </div>

        {/* Finding cards */}
        <div className="space-y-3">
          {typeFindings.map((finding, index) => (
            <FindingCard
              key={finding.id}
              finding={finding}
              index={index}
              isExpanded={expandedFinding === finding.id}
              onToggleExpand={() => setExpandedFinding(expandedFinding === finding.id ? null : finding.id)}
              findingPocs={pocs[finding.id] || []}
              userId={userId}
              projectName={projectName}
              getUsername={getUsername}
              onDelete={handleDeleteRequest}
              onAddPoc={onPocAdded}
              onRemovePoc={onPocRemoved}
              onUpdateRetest={handleUpdateRetestStatus}
            />
          ))}
        </div>

        {/* Empty state */}
        {typeFindings.length === 0 && (
          <Card className="p-12 text-center">
            <div className="flex flex-col items-center gap-2">
              {config.icon}
              <p className="text-lg font-medium">No {config.label} findings yet</p>
              <p className="text-sm text-muted-foreground mt-1">
                Start documenting {config.label.toLowerCase()} vulnerabilities found during the assessment
              </p>
              <Button variant="default" className="gradient-technieum mt-4" onClick={() => openAddFindingDialog(type)}>
                <Plus className="h-4 w-4 mr-2" />Add {config.label} Finding
              </Button>
            </div>
          </Card>
        )}
      </div>
    );
  };

  // ── TOIP renderer ──
  const renderToipTab = () => {
    const categories = Array.from(new Set(TOIP_TEST_CASES.map(t => t.category)));
    const secureCount   = toipTestCases.filter(t => t.status === 'Secure').length;
    const insecureCount = toipTestCases.filter(t => t.status === 'Not Secure').length;
    const pendingCount  = toipTestCases.filter(t => t.status === null).length;
    const totalCount    = toipTestCases.length;
    const progressPct   = totalCount > 0 ? Math.round(((secureCount + insecureCount) / totalCount) * 100) : 0;

    const filtered = toipTestCases.filter(tc => {
      const matchSearch   = tc.title.toLowerCase().includes(toipSearch.toLowerCase()) ||
        tc.description.toLowerCase().includes(toipSearch.toLowerCase());
      const matchCategory = toipCategoryFilter === 'all' || tc.category === toipCategoryFilter;
      const matchSeverity = toipSeverityFilter === 'all' || tc.severity === toipSeverityFilter;
      return matchSearch && matchCategory && matchSeverity;
    });

    const groupedFiltered: Record<string, ToipTestCase[]> = {};
    filtered.forEach(tc => {
      if (!groupedFiltered[tc.category]) groupedFiltered[tc.category] = [];
      groupedFiltered[tc.category].push(tc);
    });

    const severityColors: Record<string, string> = {
      Critical: 'bg-red-500/10 text-red-400 border-red-500/30',
      High:     'bg-orange-500/10 text-orange-400 border-orange-500/30',
      Medium:   'bg-yellow-500/10 text-yellow-400 border-yellow-500/30',
      Low:      'bg-gray-500/10 text-gray-400 border-gray-500/30',
    };

    return (
      <div className="space-y-5">
        {/* Header banner — uses TOIP_CONFIG orange, not purple */}
        <div className="flex items-start justify-between gap-4 p-4 rounded-xl bg-orange-500/5 border border-orange-500/20">
          <div className="flex items-center gap-3">
            <div className="h-10 w-10 rounded-lg bg-orange-500/20 border border-orange-500/30 flex items-center justify-center">
              <Radar className="h-5 w-5 text-orange-400" />
            </div>
            <div>
              <p className="font-semibold text-orange-300 text-sm">Technieum OffSec Intelligence Portal</p>
              <p className="text-xs text-muted-foreground mt-0.5">
                AI-generated test cases for this project — mark each as <span className="text-green-400 font-medium">Secure</span> or <span className="text-red-400 font-medium">Not Secure</span>
              </p>
            </div>
          </div>
          <Badge variant="outline" className={`${TOIP_CONFIG.color} ${TOIP_CONFIG.borderColor} ${TOIP_CONFIG.bgColor} shrink-0`}>
            {totalCount} Test Cases
          </Badge>
        </div>

        {/* Progress + stat strip */}
        <div className="space-y-3">
          <div className="grid grid-cols-3 gap-3 text-center">
            <div className="p-3 rounded-lg bg-green-500/10 border border-green-500/20">
              <p className="text-2xl font-bold text-green-400">{secureCount}</p>
              <p className="text-xs text-muted-foreground mt-0.5">Secure</p>
            </div>
            <div className="p-3 rounded-lg bg-red-500/10 border border-red-500/20">
              <p className="text-2xl font-bold text-red-400">{insecureCount}</p>
              <p className="text-xs text-muted-foreground mt-0.5">Not Secure</p>
            </div>
            <div className="p-3 rounded-lg bg-secondary/40 border border-border/40">
              <p className="text-2xl font-bold text-muted-foreground">{pendingCount}</p>
              <p className="text-xs text-muted-foreground mt-0.5">Pending</p>
            </div>
          </div>

          <div>
            <div className="flex justify-between items-center mb-1.5">
              <span className="text-xs text-muted-foreground">Assessment Progress</span>
              <span className={`text-xs font-semibold ${TOIP_CONFIG.color}`}>{progressPct}% tested</span>
            </div>
            <div className="w-full h-2 bg-secondary rounded-full overflow-hidden flex">
              <div
                className="h-full bg-green-500 transition-all duration-500 rounded-l-full"
                style={{ width: `${Math.round((secureCount / totalCount) * 100)}%` }}
              />
              <div
                className="h-full bg-red-500 transition-all duration-500"
                style={{ width: `${Math.round((insecureCount / totalCount) * 100)}%` }}
              />
            </div>
            <div className="flex gap-4 mt-1.5">
              <span className="flex items-center gap-1 text-xs text-muted-foreground">
                <span className="w-2 h-2 rounded-full bg-green-500 inline-block" />Secure
              </span>
              <span className="flex items-center gap-1 text-xs text-muted-foreground">
                <span className="w-2 h-2 rounded-full bg-red-500 inline-block" />Not Secure
              </span>
              <span className="flex items-center gap-1 text-xs text-muted-foreground">
                <span className="w-2 h-2 rounded-full bg-secondary inline-block" />Pending
              </span>
            </div>
          </div>
        </div>

        {/* Filters */}
        <div className="flex flex-col sm:flex-row gap-3">
          <div className="relative flex-1">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
            <Input
              placeholder="Search test cases..."
              value={toipSearch}
              onChange={e => setToipSearch(e.target.value)}
              className="pl-10 bg-secondary/50"
            />
          </div>
          <Select value={toipCategoryFilter} onValueChange={setToipCategoryFilter}>
            <SelectTrigger className="w-full sm:w-48 bg-secondary/50"><SelectValue placeholder="Category" /></SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Categories</SelectItem>
              {categories.map(c => <SelectItem key={c} value={c}>{c}</SelectItem>)}
            </SelectContent>
          </Select>
          <Select value={toipSeverityFilter} onValueChange={setToipSeverityFilter}>
            <SelectTrigger className="w-full sm:w-36 bg-secondary/50"><SelectValue placeholder="Severity" /></SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Severity</SelectItem>
              <SelectItem value="Critical">Critical</SelectItem>
              <SelectItem value="High">High</SelectItem>
              <SelectItem value="Medium">Medium</SelectItem>
              <SelectItem value="Low">Low</SelectItem>
            </SelectContent>
          </Select>
        </div>

        {/* Test cases grouped by category */}
        {Object.keys(groupedFiltered).length === 0 ? (
          <Card className="p-12 text-center">
            <Radar className="h-10 w-10 mx-auto text-muted-foreground/40 mb-3" />
            <p className="text-sm text-muted-foreground">No test cases match your filters.</p>
          </Card>
        ) : (
          <div className="space-y-4">
            {Object.entries(groupedFiltered).map(([category, cases]) => {
              const catSecure   = cases.filter(t => t.status === 'Secure').length;
              const catInsecure = cases.filter(t => t.status === 'Not Secure').length;
              return (
                <Card key={category} className="overflow-hidden border border-border/50">
                  {/* Category header */}
                  <div className="flex items-center justify-between px-4 py-3 bg-secondary/30 border-b border-border/40">
                    <div className="flex items-center gap-2">
                      <span className="text-sm font-semibold">{category}</span>
                      <Badge variant="outline" className="text-xs">{cases.length} tests</Badge>
                    </div>
                    <div className="flex items-center gap-2 text-xs text-muted-foreground">
                      {catSecure > 0   && <span className="text-green-400 font-medium">{catSecure} secure</span>}
                      {catInsecure > 0 && <span className="text-red-400 font-medium">{catInsecure} insecure</span>}
                    </div>
                  </div>

                  {/* Test case rows */}
                  <div className="divide-y divide-border/30">
                    {cases.map(tc => (
                      <div
                        key={tc.id}
                        className={`flex items-start gap-4 px-4 py-3 transition-colors group
                          ${tc.status === 'Secure'     ? 'bg-green-500/5' :
                            tc.status === 'Not Secure' ? 'bg-red-500/5'   : 'hover:bg-secondary/30'}`}
                      >
                        {/* Status indicator line */}
                        <div className={`w-1 self-stretch rounded-full shrink-0 mt-1
                          ${tc.status === 'Secure'     ? 'bg-green-500' :
                            tc.status === 'Not Secure' ? 'bg-red-500'   : 'bg-border/50'}`}
                        />

                        {/* Content */}
                        <div className="flex-1 min-w-0">
                          <div className="flex items-center gap-2 flex-wrap mb-1">
                            <span className="text-sm font-medium">{tc.title}</span>
                            <span className={`text-xs px-1.5 py-0.5 rounded-full border font-medium ${severityColors[tc.severity]}`}>
                              {tc.severity}
                            </span>
                            {tc.status && (
                              <span className={`text-xs px-1.5 py-0.5 rounded-full border font-medium
                                ${tc.status === 'Secure'
                                  ? 'bg-green-500/10 text-green-400 border-green-500/30'
                                  : 'bg-red-500/10 text-red-400 border-red-500/30'}`}>
                                {tc.status === 'Secure' ? '✓ Secure' : '✗ Not Secure'}
                              </span>
                            )}
                          </div>
                          <p className="text-xs text-muted-foreground leading-relaxed">{tc.description}</p>
                        </div>

                        {/* Action buttons */}
                        <div className="flex items-center gap-2 shrink-0 pt-0.5">
                          <button
                            onClick={() => toggleToipStatus(tc.id, 'Secure')}
                            title="Mark as Secure"
                            className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium border transition-all
                              ${tc.status === 'Secure'
                                ? 'bg-green-500/20 text-green-400 border-green-500/40 shadow-sm'
                                : 'bg-secondary/50 text-muted-foreground border-border/40 hover:bg-green-500/10 hover:text-green-400 hover:border-green-500/30'}`}
                          >
                            <ShieldCheck className="h-3.5 w-3.5" />
                            Secure
                          </button>

                          <button
                            onClick={() => toggleToipStatus(tc.id, 'Not Secure')}
                            title="Mark as Not Secure"
                            className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium border transition-all
                              ${tc.status === 'Not Secure'
                                ? 'bg-red-500/20 text-red-400 border-red-500/40 shadow-sm'
                                : 'bg-secondary/50 text-muted-foreground border-border/40 hover:bg-red-500/10 hover:text-red-400 hover:border-red-500/30'}`}
                          >
                            <ShieldX className="h-3.5 w-3.5" />
                            Not Secure
                          </button>
                        </div>
                      </div>
                    ))}
                  </div>
                </Card>
              );
            })}
          </div>
        )}

        {/* Info footer */}
        <div className="flex items-center gap-2 p-3 rounded-lg bg-secondary/30 border border-border/40">
          <Info className="h-4 w-4 text-muted-foreground shrink-0" />
          <p className="text-xs text-muted-foreground">
            Test cases are generated by the <span className={`${TOIP_CONFIG.color} font-medium`}>Technieum OffSec Intelligence Portal</span> based on this project's scope. Results are saved locally to this session.
          </p>
        </div>
      </div>
    );
  };

  // ─── Render ────────────────────────────────────────────────────────────────

  const toipPending = toipTestCases.filter(t => t.status === null).length;
  const scaCount    = getFindingsByType('sast').length;

  return (
    <>
      <Tabs value={activeFindingTab} onValueChange={setActiveFindingTab} className="space-y-4">
        <TabsList className="bg-secondary/50 h-auto gap-1 p-1 flex-wrap">

          {/* Standard finding type tabs */}
          {(['pentest', 'sast', 'asm', 'llm'] as FindingType[]).map(type => {
            const config = findingTypeConfig[type];
            const count  = getFindingsByType(type).length;
            return (
              <TabsTrigger key={type} value={type} className="flex items-center gap-2 text-sm">
                {config.icon}{config.label}
                <span className={`ml-1 px-1.5 py-0.5 rounded-full text-xs ${config.bgColor} ${config.color} font-semibold`}>
                  {count}
                </span>
              </TabsTrigger>
            );
          })}

          {/* SCA tab — uses SCA_CONFIG colors */}
          <TabsTrigger value="sca" className="flex items-center gap-2 text-sm">
            {SCA_CONFIG.icon}
            {SCA_CONFIG.label}
            <span className={`ml-1 px-1.5 py-0.5 rounded-full text-xs ${SCA_CONFIG.bgColor} ${SCA_CONFIG.color} font-semibold`}>
              {scaCount}
            </span>
          </TabsTrigger>

          {/* TOIP tab — uses TOIP_CONFIG colors */}
          <TabsTrigger value="toip" className="flex items-center gap-2 text-sm">
            {TOIP_CONFIG.icon}
            {TOIP_CONFIG.label}
            {toipPending > 0 && (
              <span className={`ml-1 px-1.5 py-0.5 rounded-full text-xs ${TOIP_CONFIG.bgColor} ${TOIP_CONFIG.color} font-semibold`}>
                {toipPending} pending
              </span>
            )}
          </TabsTrigger>
        </TabsList>

        {/* Standard tabs */}
        <TabsContent value="pentest" className="space-y-4 mt-0">{renderFindingsList('pentest')}</TabsContent>
        <TabsContent value="sast"    className="space-y-4 mt-0">{renderFindingsList('sast')}</TabsContent>
        <TabsContent value="asm"     className="space-y-4 mt-0">{renderFindingsList('asm')}</TabsContent>
        <TabsContent value="llm"     className="space-y-4 mt-0">{renderFindingsList('llm')}</TabsContent>

        {/* SCA tab — fetches 'sast' findings but displays everything as "SCA" */}
        <TabsContent value="sca" className="space-y-4 mt-0">
          {/* Header banner — primary orange to match the app's design language */}
          <div className="flex items-center gap-3 p-4 rounded-xl bg-orange-500/5 border border-orange-500/20 mb-2">
            <div className="h-9 w-9 rounded-lg bg-orange-500/20 border border-orange-500/30 flex items-center justify-center">
              <Package className="h-4 w-4 text-orange-400" />
            </div>
            <div>
              <p className="font-semibold text-orange-300 text-sm">Software Composition Analysis</p>
              <p className="text-xs text-muted-foreground mt-0.5">
                Track open-source dependency vulnerabilities, outdated packages, and license risks.
              </p>
            </div>
          </div>
          {/* Pass SCA_CONFIG as displayConfig so all labels/buttons say "SCA" */}
          {renderFindingsList('sast', SCA_CONFIG)}
        </TabsContent>

        {/* TOIP */}
        <TabsContent value="toip" className="space-y-4 mt-0">
          {renderToipTab()}
        </TabsContent>
      </Tabs>

      <AddFindingDialog
        open={addFindingOpen}
        onClose={() => setAddFindingOpen(false)}
        projectId={projectId}
        projectName={projectName}
        userId={userId}
        findingType={currentFindingType}
        onSuccess={async (finding, newPocs) => {
          onFindingAdded(finding, newPocs);
          await onRefresh();
        }}
      />

      <DeleteConfirmDialog
        open={!!deletingFindingId}
        onClose={() => setDeletingFindingId(null)}
        onConfirm={confirmDelete}
      />
    </>
  );
}